"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { api, apiBase, ApiError, getToken } from "@/lib/api";
import { commerceError } from "@/lib/commerce";
import { formatWhen, money } from "@/lib/format";
import { STATUS_LABEL } from "@/lib/status";

type EventRow = { id: string; title: string; status: string; city: string; event_date: string; declared_budget_rub: number | null; confirmed_rub: number | null; recorded_payments_rub: number; test_payments_rub: number; requests: number; completed: number };
type Supplier = { key: string; name: string; href: string | null; requests: number; offers: number; completed: number; cancelled: number; confirmed: number; confirmed_rub: number | null; event_count: number; events: { id: string; title: string; event_date: string }[] };
type Report = { enabled: { analytics: boolean; history: boolean; exports: boolean }; period?: { from: string; to: string }; methodology?: string; totals?: { events: number; completed_events: number; confirmed_rub: number | null; recorded_payments_rub: number; test_payments_rub: number; pending_payments_rub: number; requests: number; offers: number; completed: number }; events?: EventRow[]; suppliers?: Supplier[] };
const amount = (value: number | null) => value === null ? "Сумма неполная" : money(value);
export function BusinessReporting({ orgId }: { orgId: string }) {
  const [data, setData] = useState<Report | null>(null); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [query, setQuery] = useState(""); const [refresh, setRefresh] = useState(0); const [page, setPage] = useState(0); const [supplierPage, setSupplierPage] = useState(0); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { const c = new AbortController(); setLoading(true); api<Report>(`/business/organizations/${orgId}/report${query}`, { signal: c.signal }).then(result => { if (!c.signal.aborted) { setData(result); setError(""); if (result.period) { setFrom(result.period.from); setTo(result.period.to); } setPage(0); setSupplierPage(0); } }).catch(e => { if (!c.signal.aborted) { setData(null); setError(commerceError(e)); } }).finally(() => { if (!c.signal.aborted) setLoading(false); }); return () => c.abort(); }, [orgId, query, refresh]);
  async function download() { setBusy(true); setError(""); try { const response = await fetch(`${apiBase()}/business/organizations/${orgId}/documents.zip?date_from=${data?.period?.from || from}&date_to=${data?.period?.to || to}`, { headers: { Authorization: `Bearer ${getToken()}` } }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new ApiError(body.detail || "Не удалось создать архив", response.status); } const url = URL.createObjectURL(await response.blob()); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "buker-event-documents.zip"; anchor.click(); URL.revokeObjectURL(url); } catch(e) { setError(commerceError(e)); } finally { setBusy(false); } }
  return <section className="card commerce-checkout" aria-label="События и история поставщиков"><h2>События и история поставщиков</h2>
    {loading && <p role="status">Собираем данные событий…</p>}{error && <p role="alert">{error}</p>}
    {data && !data.enabled.analytics && !data.enabled.history && !data.enabled.exports ? <p>Сводная аналитика и история поставщиков доступны в <Link href="/pricing">Business</Link>. Отдельные события и сделки остаются в вашем кабинете.</p> : data && <>
      <form onSubmit={e => { e.preventDefault(); setQuery(`?date_from=${from}&date_to=${to}`); setRefresh(v => v + 1); }} className="commerce-checkout"><label className="commerce-org">События с даты, по Москве<input type="date" required value={from} onChange={e => setFrom(e.target.value)} /></label><label className="commerce-org">События по дату включительно<input type="date" required value={to} onChange={e => setTo(e.target.value)} /></label><button className="btn" disabled={loading || busy}>Применить период</button></form>
      <p className="timeline">{data.methodology}</p>
      {data.totals && <div aria-label="Сводка событий"><p>Событий: {data.totals.events}. Завершено событий: {data.totals.completed_events}. Завершено сделок: {data.totals.completed}.</p><dl className="business-metrics"><div><dt>Подтверждённые условия сделок</dt><dd>{amount(data.totals.confirmed_rub)}</dd></div><div><dt>Записанные успешные оплаты</dt><dd>{money(data.totals.recorded_payments_rub)}</dd></div><div><dt>Тестовые оплаты — без списания денег</dt><dd>{money(data.totals.test_payments_rub)}</dd></div><div><dt>Ожидаемые нетестовые оплаты</dt><dd>{money(data.totals.pending_payments_rub)}</dd></div></dl><p>Заявок: {data.totals.requests}. Полученных предложений: {data.totals.offers}.</p></div>}
      {data.events && <section aria-label="Список событий отчёта"><h3>События</h3>{!data.events.length && <p>В выбранном периоде событий нет.</p>}{data.events.slice(page * 25, (page + 1) * 25).map(event => <article key={event.id} style={{ marginTop: "1rem" }}><h4><Link href={`/events/${event.id}`}>{event.title}</Link></h4><p>{formatWhen(event.event_date)} · {event.city} · {STATUS_LABEL[event.status] || "Статус уточняется"}</p><p>Бюджет: {event.declared_budget_rub === null ? "не указан" : money(event.declared_budget_rub)}. Подтверждённые условия: {amount(event.confirmed_rub)}.</p><p className="timeline">Записанные оплаты: {money(event.recorded_payments_rub)}. Тестовые: {money(event.test_payments_rub)}. Заявок: {event.requests}; завершённых сделок: {event.completed}.</p></article>)}<div className="commerce-actions">{page > 0 && <button className="btn secondary" onClick={() => setPage(v => v - 1)}>Предыдущие события</button>}{(page + 1) * 25 < data.events.length && <button className="btn secondary" onClick={() => setPage(v => v + 1)}>Следующие события</button>}</div></section>}
      {data.suppliers && <section aria-label="История поставщиков"><h3>История поставщиков</h3>{!data.suppliers.length && <p>В выбранных событиях ещё нет обращений к поставщикам.</p>}{data.suppliers.slice(supplierPage * 25, (supplierPage + 1) * 25).map(item => <article key={item.key} style={{ marginTop: "1rem", overflowWrap: "anywhere" }}><h4>{item.href ? <Link href={item.href}>{item.name}</Link> : item.name}</h4><p>Событий: {item.event_count}. Заявок: {item.requests}. Предложений: {item.offers}. Завершённых сделок: {item.completed}. Отменённых сделок: {item.cancelled}.</p><p>Подтверждённые условия: {amount(item.confirmed_rub)}.</p><details><summary>Посмотреть связанные события</summary><ul>{item.events.map(event => <li key={event.id}><Link href={`/events/${event.id}`}>{event.title}</Link> · {formatWhen(event.event_date)}</li>)}</ul></details></article>)}<div className="commerce-actions">{supplierPage > 0 && <button className="btn secondary" onClick={() => setSupplierPage(v => v - 1)}>Предыдущие поставщики</button>}{(supplierPage + 1) * 25 < data.suppliers.length && <button className="btn secondary" onClick={() => setSupplierPage(v => v + 1)}>Следующие поставщики</button>}</div></section>}
      {data.enabled.exports && <section><h3>Экспорт договоров и условий</h3><p>ZIP: сохранённый текст договоров со статусами подписания, все версии предложений и сводка событий. До 100 событий и 20 МБ. Вложения и переписка остаются в комнатах сделок.</p><button className="btn" disabled={busy || loading} onClick={() => void download()}>{busy ? "Готовим архив…" : "Скачать договоры и условия"}</button></section>}
    </>}
    <p><button className="btn secondary" disabled={loading || busy} onClick={() => setRefresh(v => v + 1)}>Обновить отчёт</button></p>
  </section>;
}
