"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import "@/components/event-studio/event-studio-map.css";
import PuzzleBoard from "@/components/event-studio/PuzzleBoard";
import { MOSCOW_DISTRICTS } from "@/lib/moscowDistricts";
import { EMPTY_DRAFT } from "@/components/event-studio/types";
import { loadStoredDraft, saveStoredDraft } from "@/components/event-studio/adapter";
import { moscowToday } from "@/lib/format";
const steps = ["Повод", "Дата", "Гости", "Район", "Музыка", "Моменты"];
const choices: Record<number,string[]> = {0:["День рождения","Свадьба","Корпоратив","Вечеринка"],4:["Диджей","Живая группа","Свой плейлист"],5:["Фотограф","Фото и видео","Снимаем сами"]};
export default function AssemblePage(){
 const router=useRouter();const [step,setStep]=useState(0);const [values,setValues]=useState<string[]>(Array(6).fill(""));const [ready,setReady]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{try{const data=JSON.parse((sessionStorage.getItem("booker.demo.token") ? sessionStorage : localStorage).getItem("booker.assembly")||"null");if(Array.isArray(data)&&data.length===6&&data.every(v=>typeof v==="string"))setValues(data);}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)try{(sessionStorage.getItem("booker.demo.token") ? sessionStorage : localStorage).setItem("booker.assembly",JSON.stringify(values));}catch{setError("Не удалось сохранить на устройстве. Продолжайте в этой вкладке.")}},[values,ready]);
 function update(value:string){setValues(v=>v.map((x,i)=>i===step?value:x));setError("")}
 function next(){if(step===1&&values[1]&&values[1]<moscowToday()){setError("Выберите текущую или будущую дату");return}if(step===2&&values[2]&&(!Number.isFinite(Number(values[2]))||Number(values[2])<1)){setError("Укажите число гостей от 1");return}setStep(s=>Math.min(6,s+1))}
 function start(){try{const old=loadStoredDraft()?.draft;saveStoredDraft({...EMPTY_DRAFT,...old,title:values[0]||old?.title||"Моё событие",kind:values[0]||old?.kind||"Событие",date:values[1]||old?.date||"",guests:Number(values[2])||old?.guests||20,district:values[3],requirements:Array.from(new Set([...(old?.requirements||[]),...values.slice(4).filter(Boolean)])),version:(old?.version||0)+1});router.push("/events/new?event_studio_map_v1=1");}catch{setError("Не удалось сохранить пожелания. Разрешите хранение данных для сайта.")}}
 return <main className="assembly-page"><header><p className="eyebrow">ВАША ИДЕЯ. ВАШИ ЛЮДИ.</p><h1>Ваше событие.<br/><em>Всё сложится.</em></h1><p>Выбирайте — хромовые пазлы соединятся сами.</p></header><div className="assembly-layout"><section className="assembly-board"><PuzzleBoard slots={steps.map((label,i)=>({id:String(i),label,detail:values[i]||"Выбрать",filled:Boolean(values[i])}))} onSlotSelect={s=>setStep(Number(s.id))}/><p>Нажмите на любой пазл, чтобы изменить выбор</p><progress aria-label="Частей выбрано" max={6} value={values.filter(Boolean).length}/></section><section className="assembly-editor" key={step}>{step<6?<><span className="eyebrow">ПАЗЛ 0{step+1} / 06</span><h2>{["Что отмечаем?","Когда встречаемся?","Кого собираем?","Где вам удобно?","Как будем звучать?","Что сохраним?"][step]}</h2>{choices[step]?<div className="assembly-choices">{choices[step].map(c=><button className="secondary" aria-pressed={values[step]===c} onClick={()=>update(c)} key={c}>{c}<span>{values[step]===c?"✓":"+"}</span></button>)}</div>:<label>{steps[step]}<datalist id="assembly-districts">{MOSCOW_DISTRICTS.map(x=><option key={x} value={x}/>)}</datalist><input list={step===3?"assembly-districts":undefined} type={step===1?"date":step===2?"number":"text"} min={step===1?moscowToday():step===2?1:undefined} value={values[step]} onInput={e=>update(e.currentTarget.value)} onChange={e=>update(e.target.value)} onBlur={e=>update(e.currentTarget.value)} placeholder={step===3?"Например, Хамовники":step===2?"Количество гостей":undefined}/></label>}{step===3&&<p>Район Москвы. Площадку выберем на интерактивной карте.</p>}<button onClick={next} className="assembly-next">Добавить пазл →</button><button className="linkish" onClick={()=>{setStep(s=>Math.min(6,s+1));setError("")}}>Решу позже</button></>:<><p className="eyebrow">ИДЕЯ СОБРАНА</p><h2>Теперь — ваша команда.</h2><dl>{steps.map((s,i)=><div key={s}><dt>{s}</dt><dd>{values[i]||"Решим позже"}</dd></div>)}</dl><button onClick={start}>Подобрать площадку и команду →</button><p>Выбор ещё не означает бронирование. Условия подтвердят участники.</p></>}{error&&<p role="alert">{error}</p>}</section></div></main>
}
