import { expect, test } from "@playwright/test";
import { API_BASE, getJson, injectSession, postJson, register } from "./helpers";

for (const width of [1440, 390]) {
  test.describe(`Business workflows ${width}px`, () => {
    test.use({ viewport: { width, height: 900 } });
    test("templates, clean drafts and private notes survive response loss", async ({ page, request }, testInfo) => {
      test.setTimeout(120_000);
      const suffix = `${width}-${Date.now()}`;
      const user = await register(request, `business-${suffix}@booker.test`, "Организатор Анна");
      const org = await postJson<{ id: string }>(request, "/orgs", user.token, { name: "Агентство событий", kind: "customer" });
      const day = new Date(Date.now() + 20 * 86400000).toISOString().slice(0, 10);
      const later = new Date(Date.now() + 40 * 86400000).toISOString().slice(0, 10);
      const event = await postJson<{ id: string }>(request, "/events", user.token, { organization_id: org.id, title: "Корпоратив осенью", city: "Москва", event_type: "Корпоратив", event_date: `${day}T15:00:00Z`, ends_at: `${day}T18:00:00Z`, budget_rub: 250000, guest_count: 80, requirements: [{ category_code: "dj" }, { category_code: "venue" }] });
      await injectSession(page, user.token, org.id);
      await page.goto("/cabinet/customer/business");
      const workspace = page.getByRole("region", { name: "Шаблоны и копирование событий", exact: true });
      await expect(workspace).toContainText("Для создания шаблонов и копий нужен");
      const order = await postJson<{ id: string }>(request, `/commerce/organizations/${org.id}/orders`, user.token, { plan_code: "customer_business", billing_period: "monthly", idempotency_key: `business-${suffix}` });
      await postJson(request, `/commerce/orders/${order.id}/test-complete`, user.token, { status: "paid" });
      await page.goto(`/events/${event.id}`);
      const notes = page.getByRole("region", { name: "Внутренние заметки команды", exact: true });
      await notes.getByLabel("Новая внутренняя заметка", { exact: true }).fill("Заказчик просит обсудить порядок выступлений на встрече команды.");
      let loseNote = true;
      await page.route(`${API_BASE}/business/events/${event.id}/notes`, async route => { if (route.request().method() === "POST" && loseNote) { loseNote = false; expect((await route.fetch()).status()).toBe(201); await route.abort("failed"); } else await route.continue(); });
      await notes.getByRole("button", { name: "Добавить заметку", exact: true }).click();
      await expect(notes.getByRole("alert")).toBeVisible();
      await notes.getByRole("button", { name: "Добавить заметку", exact: true }).click();
      await expect(notes.getByRole("article")).toHaveCount(1);
      await notes.getByRole("button", { name: "Изменить заметку", exact: true }).click();
      await notes.getByLabel("Текст заметки", { exact: true }).fill("Встреча команды назначена. Исполнителю условия отправим отдельным предложением.");
      await notes.getByRole("button", { name: "Сохранить заметку", exact: true }).click();
      await expect(notes).toContainText("Организатор Анна");
      await expect(notes).toContainText("Встреча команды назначена.");
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
      await notes.evaluate(el => window.scrollBy({ top: el.getBoundingClientRect().top - (document.querySelector("header.top")?.getBoundingClientRect().height || 0) - 16, behavior: "instant" }));
      await page.screenshot({ path: testInfo.outputPath("business-notes.png") });
      await page.goto("/cabinet/customer/business");
      await workspace.getByRole("combobox", { name: "Основа нового события", exact: true }).selectOption(`event:${event.id}`);
      await workspace.getByLabel("Название шаблона", { exact: true }).fill("Корпоратив для команды");
      await workspace.getByRole("button", { name: "Сохранить как шаблон", exact: true }).click();
      await expect(workspace.getByRole("heading", { name: "Корпоратив для команды", exact: true })).toBeVisible();
      await workspace.getByRole("button", { name: "Выбрать шаблон: Корпоратив для команды", exact: true }).click();
      await workspace.getByLabel("Название нового события", { exact: true }).fill("Новый корпоратив");
      await workspace.getByLabel("Новое начало, по Москве", { exact: true }).fill(`${later}T18:00`);
      await workspace.getByLabel("Новое окончание, по Москве", { exact: true }).fill(`${later}T21:00`);
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
      await workspace.evaluate(el => window.scrollBy({ top: el.getBoundingClientRect().top - (document.querySelector("header.top")?.getBoundingClientRect().height || 0) - 16, behavior: "instant" }));
      await page.screenshot({ path: testInfo.outputPath("business-template.png") });
      await workspace.locator("form").evaluate(el => window.scrollBy({ top: el.getBoundingClientRect().top - (document.querySelector("header.top")?.getBoundingClientRect().height || 0) - 16, behavior: "instant" }));
      await page.screenshot({ path: testInfo.outputPath("business-draft-form.png") });
      let loseDraft = true;
      await page.route(`${API_BASE}/business/templates/*/events`, async route => { if (loseDraft) { loseDraft = false; expect((await route.fetch()).status()).toBe(201); await route.abort("failed"); } else await route.continue(); });
      await workspace.getByRole("button", { name: "Создать черновик", exact: true }).click();
      await expect(workspace.getByRole("alert")).toBeVisible();
      await workspace.getByRole("button", { name: "Создать черновик", exact: true }).click();
      await expect(page.getByRole("heading", { name: "Новый корпоратив", exact: true })).toBeVisible();
      const newId = page.url().split("/").pop(); expect(newId).not.toBe(event.id);
      const draft = await getJson<{ status: string; requests: object[]; requirements: object[]; budget_rub: number | null }>(request, `/events/${newId}`, user.token);
      expect(draft.status).toBe("Draft"); expect(draft.requests).toHaveLength(0); expect(draft.requirements).toHaveLength(2); expect(draft.budget_rub).toBe(250000);
      expect((await getJson<{ total: number }>(request, `/business/events/${newId}/notes`, user.token)).total).toBe(0);
      expect((await getJson<{ items: object[] }>(request, `/events?organization_id=${org.id}`, user.token)).items).toHaveLength(2);
      await page.goto(`/events/${event.id}`);
      await notes.getByRole("button", { name: "Удалить заметку", exact: true }).click();
      await expect(notes).toContainText("Заметок пока нет");
      await page.goto("/cabinet/customer/business");
      await workspace.getByRole("combobox", { name: "Основа нового события", exact: true }).selectOption(`event:${event.id}`);
      await workspace.getByLabel("Название нового события", { exact: true }).fill("Копия события");
      await workspace.getByLabel("Новое начало, по Москве", { exact: true }).fill(`${later}T18:00`);
      await workspace.getByLabel("Новое окончание, по Москве", { exact: true }).fill(`${later}T21:00`);
      await workspace.getByRole("button", { name: "Создать черновик", exact: true }).click();
      await expect(page.getByRole("heading", { name: "Копия события", exact: true })).toBeVisible();
      expect((await getJson<{ items: object[] }>(request, `/events?organization_id=${org.id}`, user.token)).items).toHaveLength(3);
      await page.goto("/cabinet/customer/business");
      const report = page.getByRole("region", { name: "События и история поставщиков", exact: true });
      await expect(report).toContainText("Событий: 3.");
      await expect(report).toContainText("Тестовые оплаты — без списания денег");
      await expect(report).toContainText("ещё нет обращений к поставщикам");
      const downloaded = page.waitForEvent("download");
      await report.getByRole("button", { name: "Скачать договоры и условия", exact: true }).click();
      const archive = await downloaded;
      expect(archive.suggestedFilename()).toBe("buker-event-documents.zip");
      expect(await archive.failure()).toBeNull();
      await report.evaluate(el => window.scrollBy({ top: el.getBoundingClientRect().top - (document.querySelector("header.top")?.getBoundingClientRect().height || 0) - 16, behavior: "instant" }));
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
      await page.screenshot({ path: testInfo.outputPath("business-report.png") });
      await report.getByLabel("События с даты, по Москве", { exact: true }).fill("2020-01-01");
      await report.getByLabel("События по дату включительно", { exact: true }).fill("2020-01-02");
      await report.getByRole("button", { name: "Применить период", exact: true }).click();
      await expect(report).toContainText("В выбранном периоде событий нет.");
      await workspace.getByRole("button", { name: "В архив: Корпоратив для команды", exact: true }).click();
      await expect(workspace).toContainText("Шаблонов пока нет");
    });
  });
}
