"use client";
import { useEffect, useRef, useState } from "react";
type MapHandle={setView:(p:number[],zoom:number)=>MapHandle;remove:()=>void;invalidateSize:()=>void};
type Marker={addTo:(m:MapHandle)=>Marker;remove:()=>void;bindPopup:(s:HTMLElement)=>Marker;openPopup:()=>Marker};
type Leaflet={map:(el:HTMLElement)=>MapHandle;tileLayer:(u:string,o:Record<string,unknown>)=>{addTo:(m:MapHandle)=>void};circleMarker:(p:number[],o:Record<string,unknown>)=>Marker};
declare global {interface Window {L?:Leaflet}}
let loading:Promise<Leaflet>|null=null;
function load(){if(window.L)return Promise.resolve(window.L);if(!loading)loading=new Promise<Leaflet>((resolve,reject)=>{const script=document.createElement("script");script.src="/vendor/leaflet/leaflet.js";script.onload=()=>window.L?resolve(window.L):reject(new Error());script.onerror=()=>{loading=null;script.remove();reject(new Error())};document.head.appendChild(script)});return loading}
export type MapVenue={id:string;name:string;address?:string;district?:string;metro?:string};
export function MoscowMap({venues,district="",onSelect}:{venues:MapVenue[];district?:string;onSelect?:(id:string)=>void}){
 const element=useRef<HTMLDivElement>(null),map=useRef<MapHandle|null>(null),pin=useRef<Marker|null>(null),abort=useRef<AbortController|null>(null);
 const [message,setMessage]=useState("Выберите площадку, чтобы найти её адрес на карте"),[selected,setSelected]=useState(""),[ready,setReady]=useState(false);
 useEffect(()=>{let alive=true;let resize:ResizeObserver|undefined;load().then(L=>{if(!alive||!element.current)return;const m=L.map(element.current).setView([55.751244,37.618423],11);map.current=m;L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(m);resize=new ResizeObserver(()=>m.invalidateSize());resize.observe(element.current);setReady(true)}).catch(()=>setMessage("Карта недоступна. Выберите площадку из списка."));return()=>{alive=false;abort.current?.abort();resize?.disconnect();map.current?.remove();map.current=null}},[]);
 useEffect(()=>{if(!ready)return;abort.current?.abort();pin.current?.remove();pin.current=null;setSelected("");if(!district){map.current?.setView([55.751244,37.618423],11);return}const timer=window.setTimeout(()=>void locate(district,false),650);return()=>window.clearTimeout(timer)},[district,ready]);
 async function locate(query:string,marker:boolean){abort.current?.abort();const c=new AbortController();abort.current=c;setMessage("Находим на карте…");try{const r=await fetch(`/geo/search?q=${encodeURIComponent(query)}`,{signal:c.signal});const p=await r.json();if(c.signal.aborted)return;if(!r.ok)throw new Error(p.error);if(!p){setMessage("Точное расположение не найдено. Уточните адрес у площадки.");return}if(map.current&&window.L){map.current.setView([p.lat,p.lon],marker?15:13);pin.current?.remove();pin.current=null;if(marker){const label=document.createElement("span");label.textContent=query;pin.current=window.L.circleMarker([p.lat,p.lon],{radius:12,color:"#40582d",weight:3,fillColor:"#d9fa79",fillOpacity:1}).addTo(map.current).bindPopup(label).openPopup()}setMessage(marker?"Расположение найдено по адресу — уточните вход у площадки":"Показан выбранный район Москвы")}}catch(e){if(!c.signal.aborted)setMessage(e instanceof Error?e.message:"Адрес не найден")}}
 return <section className="moscow-map-panel" aria-label="Интерактивная карта Москвы"><div className="map-tools"><h3>Москва на карте</h3><label>Площадка<select value={selected} onChange={e=>{const v=venues.find(x=>x.id===e.target.value);setSelected(e.target.value);if(v)void locate(v.address||v.name,true)}}><option value="">Выберите из {venues.length} вариантов</option>{venues.map(v=><option key={v.id} value={v.id}>{v.name}{v.district?` · ${v.district}`:""}</option>)}</select></label></div><div ref={element} className="moscow-map" aria-label="Карта: перемещайте и меняйте масштаб"/><p role="status">{message}</p>{selected&&(onSelect?<button onClick={()=>onSelect(selected)}>Добавить площадку в событие</button>:<a className="btn" href={`/venues/${encodeURIComponent(selected)}`}>Открыть профиль площадки ↗</a>)}<small>Карта и поиск адресов: OpenStreetMap / Nominatim. Артисты подбираются по городу; выезд в район согласуется отдельно.</small></section>
}
