"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ApiError } from "@/lib/api";
import { commerceError } from "@/lib/commerce";
import { formatWhen } from "@/lib/format";
import { guestApi, REACTIONS, type Reaction, type Shared, type SharedItem } from "@/lib/shortlists";

export function FeedbackResults({ item }: { item: SharedItem }) {
  return <div className="shortlist-results"><p>{Object.entries(REACTIONS).map(([key, label]) => <span key={key}>{label}: {item.counts[key as Exclude<Reaction, null>]} · </span>)}</p>{item.feedback.length === 0 ? <p>Мнений пока нет.</p> : <ul>{item.feedback.map((entry, i) => <li key={i}><strong>{entry.name}</strong>{entry.reaction && <> — {REACTIONS[entry.reaction]}</>}{entry.comment && <p className="shortlist-comment">{entry.comment}</p>}</li>)}</ul>}</div>;
}
function Candidate({ item, canWrite, busy, save }: { item: SharedItem; canWrite: boolean; busy: boolean; save: (item: SharedItem, reaction: Reaction, comment: string) => Promise<void> }) {
  const [comment, setComment] = useState(item.mine.comment);
  useEffect(() => setComment(item.mine.comment), [item.mine.comment]);
  return <article className="card shortlist-candidate" aria-label={`Кандидат: ${item.name}`}><h2>{item.name}</h2><p>{item.city}{item.summary && ` · ${item.summary}`}</p><Link href={item.profile_path} referrerPolicy="no-referrer">Открыть профиль</Link><FeedbackResults item={item} />{canWrite && <><div className="shortlist-reactions" aria-label="Ваш голос">{Object.entries(REACTIONS).map(([kind, label]) => <button className="secondary" aria-pressed={item.mine.reaction === kind} disabled={busy} key={kind} onClick={() => void save(item, item.mine.reaction === kind ? null : kind as Reaction, item.mine.comment)}>{label}</button>)}</div><label>Ваш комментарий<textarea maxLength={1000} rows={3} value={comment} onChange={(e) => setComment(e.target.value)} disabled={busy} /></label><p>Без телефонов, почты и внешних ссылок. Комментарий увидят все, у кого есть ссылка.</p><button className="btn" disabled={busy || comment === item.mine.comment} onClick={() => void save(item, item.mine.reaction, comment)}>Сохранить комментарий</button>{item.mine.comment && <button className="secondary" disabled={busy} onClick={() => void save(item, item.mine.reaction, "")}>Удалить мой комментарий</button>}</>}</article>;
}
export function SharedShortlistClient({ token }: { token: string }) {
  const [data, setData] = useState<Shared | null>(null); const [secret, setSecret] = useState(""); const [name, setName] = useState("");
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async (key: string, signal?: AbortSignal) => { setLoading(true); setError(""); try { const result = await guestApi<Shared>(token, "", key, { signal }); if (!signal?.aborted) setData(result); } catch(e) { if (!signal?.aborted) { setError(commerceError(e)); setData(null); } } finally { if (!signal?.aborted) setLoading(false); } }, [token]);
  useEffect(() => { const c = new AbortController(); let key = ""; try { key = localStorage.getItem(`booker.share.guest:${token}`) || ""; } catch { /* joining can use an in-memory capability */ } setSecret(key); void load(key, c.signal); return () => c.abort(); }, [token, load]);
  function failed(e: unknown) { setError(commerceError(e)); if (e instanceof ApiError && e.status === 404) setData(null); }
  async function join(e: React.FormEvent) { e.preventDefault(); if (busy) return; setBusy(true); setError(""); try { const key = secret || Array.from(crypto.getRandomValues(new Uint8Array(32)), (v) => v.toString(16).padStart(2, "0")).join(""); setSecret(key); try { localStorage.setItem(`booker.share.guest:${token}`, key); } catch { /* memory remains usable */ } const result = await guestApi<Shared>(token, "/guests", "", { method: "POST", body: JSON.stringify({ display_name: name, guest_secret: key }) }); setData(result); setNotice("Вы присоединились к обсуждению."); } catch(e) { failed(e); } finally { setBusy(false); } }
  async function save(item: SharedItem, reaction: Reaction, comment: string) { if (busy) return; setBusy(true); setError(""); setNotice(""); try { setData(await guestApi<Shared>(token, `/items/${item.target_id}/feedback`, secret, { method: "PUT", body: JSON.stringify({ reaction, comment, expected_revision: item.mine.revision }) })); setNotice("Ваше мнение сохранено."); } catch(e) { failed(e); } finally { setBusy(false); } }
  return <main className="shortlist-page"><p className="kicker">Совместный выбор</p><h1>{data?.title || "Подборка"}</h1>{loading && <p role="status">Загружаем обсуждение…</p>}{error && <div role="alert"><p>{error}</p>{!data && <p>Ссылка могла быть отозвана или истечь.</p>}</div>}{notice && data && <p role="status">{notice}</p>}{data && <><p>Ссылка действует до {formatWhen(data.expires_at)}. Вы видите выбранных кандидатов и мнения участников этой подборки.</p><p>{data.note}</p>{data.collaborative ? data.guest_name ? <p>Вы участвуете как <strong>{data.guest_name}</strong>. Можно изменить голос или удалить свой комментарий.</p> : <form className="card shortlist-join" onSubmit={(e) => void join(e)} aria-label="Присоединиться к обсуждению"><label>Имя для обсуждения<input value={name} onChange={(e) => setName(e.target.value)} maxLength={60} required disabled={busy} autoComplete="off" /></label><p>Имя будет видно по этой ссылке. Один голос на кандидата с этого устройства; вход в аккаунт не требуется.</p><button className="btn" disabled={busy || !name.trim()}>Присоединиться</button></form> : <p>Эта подборка доступна только для чтения.</p>}{data.items.length ? <div className="shortlist-grid">{data.items.map((item) => <Candidate key={item.target_id} item={item} canWrite={data.collaborative && Boolean(data.guest_name)} busy={busy || loading} save={save} />)}</div> : <p className="empty">Публичные кандидаты сейчас недоступны.</p>}<p>Голоса не меняют состав события и не создают заявки или бронирования. Решение остаётся за организатором.</p></>}<button className="secondary" disabled={busy || loading} onClick={() => void load(secret)}>Обновить обсуждение</button></main>;
}
