"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { api, getActiveOrg } from "@/lib/api";
import { commerceError } from "@/lib/commerce";
import { eventCommandKey, eventCommandSeed } from "@/lib/eventCommands";
import { formatWhen } from "@/lib/format";
import type { ManagedShare } from "@/lib/shortlists";
import { FeedbackResults } from "@/components/SharedShortlistClient";

type Favorite = { id: string; target_id: string; target_type: "artist" | "venue"; name?: string | null };
export function ShortlistManager({ favorites, eventId, organizationId }: { favorites?: Favorite[]; eventId?: string; organizationId?: string }) {
  const [enabled, setEnabled] = useState(false);
  const [shares, setShares] = useState<ManagedShare[]>([]); const [canManage, setCanManage] = useState(false); const [events, setEvents] = useState<{ id: string; title: string; organization_id: string }[]>([]);
  const [target, setTarget] = useState("artist"); const [selected, setSelected] = useState<string[]>([]); const [title, setTitle] = useState("Выбираем участников"); const [event, setEvent] = useState(eventId || ""); const [ttl, setTtl] = useState("14");
  const [org, setOrg] = useState(organizationId || ""); const [ready, setReady] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async (signal?: AbortSignal) => { setError(""); setReady(false); try { const query = new URLSearchParams(); if (organizationId) query.set("organization_id", organizationId); if (eventId) query.set("event_id", eventId); const data = await api<{ items: ManagedShare[]; can_manage: boolean; collaboration_enabled: boolean }>(`/shortlists?${query}`, { signal }); if (!signal?.aborted) { setShares(data.items); setCanManage(data.can_manage); setEnabled(data.collaboration_enabled); } } catch(e) { if (!signal?.aborted) setError(commerceError(e)); } finally { if (!signal?.aborted) setReady(true); } }, [eventId, organizationId]);
  useEffect(() => { const c = new AbortController(); setOrg(organizationId || getActiveOrg() || ""); void load(c.signal); if (favorites) { setEvent(new URLSearchParams(window.location.search).get("event") || ""); void api<{ items: { id: string; title: string; organization_id: string }[] }>("/events", { signal: c.signal }).then((r) => { if (!c.signal.aborted) setEvents(r.items); }).catch((e) => { if (!c.signal.aborted) setError(commerceError(e)); }); } return () => c.abort(); }, [load, organizationId, Boolean(favorites)]);
  useEffect(() => { if (favorites) setSelected((ids) => ids.filter((id) => favorites.some((f) => f.id === id))); }, [favorites]);
  async function create(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { const payload = { ...(org ? { organization_id: org } : {}), event_id: event || null, target_type: target, title, ttl_days: Number(ttl), collaborative: true, favorite_ids: selected }; const keyName = `booker.shortlist.create:${org}`; const key = await eventCommandKey(eventCommandSeed(keyName), payload); await api<ManagedShare>("/shortlists", { method: "POST", headers: { "Idempotency-Key": key }, body: JSON.stringify(payload) }); sessionStorage.removeItem(keyName); setSelected([]); setNotice("Подборка создана. Передайте ссылку тем, чьё мнение хотите узнать."); await load(); } catch(e) { setError(commerceError(e)); } finally { setBusy(false); } }
  async function revoke(id: string) { setBusy(true); setError(""); try { await api(`/shortlists/${id}/revoke`, { method: "POST" }); setNotice("Ссылка отозвана. Гостевое чтение и изменения больше недоступны."); await load(); } catch(e) { setError(commerceError(e)); } finally { setBusy(false); } }
  const available = favorites?.filter((f) => f.target_type === target) || [];
  return <section className="shortlist-manager card" aria-label="Совместный выбор участников"><h2>Совместный выбор участников</h2><p>Пригласите коллег или близких обсудить несколько кандидатов. Им доступна только подборка, без бюджета, документов и переписки события.</p>{!ready && <p role="status">Загружаем подборки…</p>}{error && <p role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}{ready && !canManage && <p>У вас доступ к просмотру результатов. Создать или отозвать ссылку может менеджер организации.</p>}
    {ready && !enabled && <p>Совместные обсуждения временно отключены. Результаты прошлых подборок доступны для просмотра.</p>}{favorites && canManage && enabled && <form onSubmit={(e) => void create(e)} aria-label="Новая совместная подборка"><label>Название подборки<input maxLength={120} required value={title} disabled={busy} onChange={(e) => setTitle(e.target.value)} /></label><label>Событие для подборки<select value={event} onChange={(e) => setEvent(e.target.value)} disabled={busy}><option value="">Без привязки к событию</option>{events.filter((e) => !org || e.organization_id === org).map((e) => <option key={e.id} value={e.id}>{e.title}</option>)}</select></label><label>Кого обсуждаем<select value={target} disabled={busy} onChange={(e) => { setTarget(e.target.value); setSelected([]); }}><option value="artist">Исполнителей</option><option value="venue">Площадки</option></select></label><fieldset disabled={busy}><legend>Выберите от двух до четырёх кандидатов</legend>{available.length ? available.map((f) => <label className="shortlist-pick" key={f.id}><input type="checkbox" checked={selected.includes(f.id)} disabled={!selected.includes(f.id) && selected.length >= 4} onChange={(e) => setSelected(e.target.checked ? [...selected, f.id] : selected.filter((id) => id !== f.id))} />{f.name || "Профиль"}</label>) : <p>Сначала добавьте кандидатов в избранное.</p>}</fieldset><label>Срок действия<select value={ttl} disabled={busy} onChange={(e) => setTtl(e.target.value)}><option value="1">1 день</option><option value="7">7 дней</option><option value="14">14 дней</option><option value="30">30 дней</option></select></label><p>Любой получатель ссылки сможет представиться, голосовать и комментировать. Не добавляйте в название контакты или приватные сведения.</p><button className="btn" disabled={busy || selected.length < 2}>Создать ссылку для обсуждения</button></form>}
    {!favorites && canManage && enabled && <p><Link href={`/cabinet/customer/favorites?event=${eventId || ""}`}>Создать подборку из избранного</Link></p>}
    {ready && shares.length === 0 && <p className="empty">Совместных подборок пока нет.</p>}{shares.map((share) => <article key={share.id} className="shortlist-managed" aria-label={`Подборка: ${share.title}`}><h3>{share.title}</h3><p>{share.active ? `Действует до ${formatWhen(share.expires_at)}` : "Ссылка недоступна: отозвана или срок истёк"}</p>{share.active && share.share_path && <><Link href={share.share_path}>Открыть гостевую подборку</Link><label>Ссылка для приглашения<input readOnly value={typeof window === "undefined" ? share.share_path : `${window.location.origin}${share.share_path}`} onFocus={(e) => e.target.select()} /></label><button className="secondary" disabled={busy} onClick={() => void navigator.clipboard.writeText(`${window.location.origin}${share.share_path}`).then(() => setNotice("Ссылка скопирована.")).catch(() => setNotice("Выделите и скопируйте ссылку из поля."))}>Скопировать ссылку</button><button className="secondary" disabled={busy} onClick={() => void revoke(share.id)}>Отозвать ссылку</button></>}{share.event_id && !eventId && <p><Link href={`/events/${share.event_id}`}>Открыть событие</Link></p>}<details><summary>Мнения участников</summary><p>{share.note}</p>{share.items.map((item) => <div key={item.target_id}><h4>{item.name}</h4><FeedbackResults item={item} /></div>)}</details></article>)}<button className="secondary" disabled={busy || !ready} onClick={() => void load()}>Обновить подборки</button></section>;
}
