"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import type {DiscoveryVenue} from "@/lib/venueDiscovery";
import {MoscowDistrictMap,moscowDistrictOptions} from "@/components/MoscowDistrictMap";
const money=new Intl.NumberFormat("ru-RU");
function VenueCard({venue:v}:{venue:DiscoveryVenue}){
 const [photo,setPhoto]=useState(0),[failed,setFailed]=useState(false),[open,setOpen]=useState(false);
 return <article className="research-venue-card"><div className="research-photo">{!failed?<img src={v.photos[photo]} alt={`Площадка «${v.name}»`} loading="lazy" decoding="async" referrerPolicy="no-referrer" onError={()=>photo+1<v.photos.length?setPhoto(photo+1):setFailed(true)}/>:<p>Источник временно не отдаёт фото. <a href={v.source} target="_blank" rel="noreferrer">Посмотреть оригинал ↗</a></p>}<span>Доступность уточняется</span></div><div className="research-card-body"><p className="research-location">{v.district||"Район уточняется"}{v.metro?` · м. ${v.metro}`:""}</p><h2>{v.name}</h2><p className="research-capacity">До {v.capacity} гостей{v.sound?" · Звук":""}{v.light?" · Свет":""}</p><p className="research-address">{v.address}</p><div className="research-price"><strong>от {money.format(v.price)} ₽<small>/час</small></strong><span>Ориентир из источника</span></div><details open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>Описание и {v.photos.length} фото</summary>{open&&<><p>{v.description}</p><div className="research-thumbnails">{v.photos.map((url,i)=><button type="button" key={url} aria-label={`Фото ${i+1}: ${v.name}`} aria-pressed={photo===i&&!failed} onClick={()=>{setFailed(false);setPhoto(i)}}><img src={url} alt="" loading="lazy" referrerPolicy="no-referrer"/></button>)}</div></>}</details><a className="research-source" href={v.source} target="_blank" rel="noreferrer">Уточнить у площадки ↗</a><small className="research-attribution">Фото и сведения: SpeedRent. Даты и итоговую стоимость подтверждает площадка.</small></div></article>
}
export default function VenueDiscovery({items,initialDistrict=""}:{items:DiscoveryVenue[];initialDistrict?:string}){
 const [query,setQuery]=useState(""),[district,setDistrict]=useState(()=>moscowDistrictOptions.find(d=>d.id===initialDistrict||d.name===initialDistrict)?.id||""),[guests,setGuests]=useState(""),[budget,setBudget]=useState(""),[sound,setSound]=useState(false),[limit,setLimit]=useState(24);
 const candidates=useMemo(()=>items.filter(v=>(!query||[v.name,v.metro,v.address].join(" ").toLocaleLowerCase("ru").includes(query.trim().toLocaleLowerCase("ru")))&&v.capacity>=(Number(guests)||0)&&(!budget||v.price<=Number(budget))&&(!sound||v.sound)),[items,query,guests,budget,sound]);
 const visible=candidates.filter(v=>!district||v.districtId===district);
 const counts=useMemo(()=>candidates.reduce<Record<string,number>>((c,v)=>{if(v.districtId)c[v.districtId]=(c[v.districtId]||0)+1;return c},{}),[candidates]);
 function choose(id:string){setDistrict(id);setLimit(24)}
 return <main className="venue-discovery"><header><p className="eyebrow">Площадки для выступлений · Москва</p><h1>Найди место<br/>для своего события.</h1><p>Подборка с фотографиями, адресами и условиями аренды. Доступность и финальную стоимость уточняйте у площадки.</p><nav aria-label="Направление поиска"><Link href="/search?kind=artist">Артисты</Link><span aria-current="page">Площадки</span><Link href="/assemble">Собрать событие ↗</Link></nav></header><p className="research-notice">Это подборка из открытых источников, отдельно от бронирования в Букере. Представители этих площадок ещё не подключены. Фото принадлежат их правообладателям.</p><div className="venue-discovery-layout"><aside className="research-filters" aria-label="Фильтры подборки"><h2>Что важно?</h2><label>Название, метро или адрес<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setLimit(24)}} placeholder="Например, Бауманская"/></label><label>Район Москвы<select aria-label="Район Москвы" value={district} onChange={e=>choose(e.target.value)}><option value="">Все районы</option>{moscowDistrictOptions.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Гостей от<input type="number" min="1" inputMode="numeric" value={guests} onChange={e=>{setGuests(e.target.value);setLimit(24)}} placeholder="Любое количество"/></label><label>Аренда до, ₽/час<input type="number" min="1" inputMode="numeric" value={budget} onChange={e=>{setBudget(e.target.value);setLimit(24)}} placeholder="Любой бюджет"/></label><label className="research-check"><input type="checkbox" checked={sound} onChange={e=>{setSound(e.target.checked);setLimit(24)}}/><span>Есть звуковое оснащение</span></label><button className="secondary" type="button" onClick={()=>{setQuery("");choose("");setGuests("");setBudget("");setSound(false)}}>Сбросить фильтры</button><small>Район определён по координатам источника. Если координат нет, площадка остаётся в общей подборке.</small></aside><div className="research-results"><MoscowDistrictMap selected={district} onSelect={choose} counts={counts}/><div className="research-result-heading"><h2>{district?moscowDistrictOptions.find(d=>d.id===district)?.name:"Площадки Москвы"}</h2><span role="status">Найдено {visible.length} из {items.length}</span></div><div className="research-grid">{visible.slice(0,limit).map(v=><VenueCard key={v.id} venue={v}/>)}</div>{!visible.length&&<div className="research-empty"><h2>По этим условиям площадок пока нет</h2><p>Выбери соседний район или измени бюджет и количество гостей.</p></div>}{visible.length>limit&&<button className="research-more" type="button" onClick={()=>setLimit(n=>n+24)}>Показать ещё {Math.min(24,visible.length-limit)} площадки</button>}</div></div></main>
}
