"use client";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/api";
import { commerceError } from "@/lib/commerce";
import { eventCommandKey, eventCommandSeed } from "@/lib/eventCommands";

type Options = { title: string; city: string; event_type: string; guest_count: number; roles: { label: string; qty: number; required: boolean }[]; participants: { source_request_id: string; name: string; can_prefer: boolean }[]; can_manage: boolean; enabled: boolean };
type Selection = { requirement_id: string | null; position: number | null; resource_type: string; resource_id: string; hall_id: string | null };
type Preferences = { items: { id: string; name: string; selection: Selection; problems: string[]; can_add: boolean; already_selected: boolean }[]; revision?: number; context_token?: string; saved_selections?: Selection[] };
export function EventRepeat({ eventId }: { eventId: string }) {
  const router = useRouter(); const [data, setData] = useState<Options | null>(null); const [title, setTitle] = useState(""); const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async (signal?: AbortSignal) => { setLoading(true); setError(""); try { const result = await api<Options>(`/events/${eventId}/repeat-options`, { signal }); if (!signal?.aborted) { setData(result); setTitle(result.title); setSelected([]); } } catch(e) { if (!signal?.aborted) setError(commerceError(e)); } finally { if (!signal?.aborted) setLoading(false); } }, [eventId]);
  useEffect(() => { const c = new AbortController(); void load(c.signal); return () => c.abort(); }, [load]);
  async function repeat(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { const payload = { title, event_date: `${start}:00+03:00`, ends_at: `${end}:00+03:00`, preferred_request_ids: selected }; const key = await eventCommandKey(eventCommandSeed(`booker.repeat:${eventId}`), payload); const result = await api<{ id: string }>(`/events/${eventId}/repeat`, { method: "POST", headers: { "Idempotency-Key": key }, body: JSON.stringify(payload) }); router.push(`/events/${result.id}`); } catch(e) { setError(commerceError(e)); } finally { setBusy(false); } }
  return <section className="card event-repeat" aria-label="Повторить событие"><h2>Повторить событие</h2><p>Создайте новое событие с прежним форматом, городом, числом гостей и ролями. Бюджет и условия сделок задаются заново.</p>{loading && <p role="status">Загружаем завершённый состав…</p>}{error && <p role="alert">{error}</p>}{data && <><p>{data.event_type || "Формат не указан"} · {data.city} · {data.guest_count} гостей</p><ul>{data.roles.map((role, index) => <li key={index}>{role.label} × {role.qty}{!role.required && " · необязательно"}</li>)}</ul>{!data.enabled ? <p>Повтор событий временно отключён.</p> : !data.can_manage ? <p>Создать повтор может менеджер организации.</p> : <form onSubmit={(e) => void repeat(e)} aria-label="Новое событие из завершённого"><fieldset disabled={busy || loading}><label>Название нового события<input maxLength={255} required value={title} onChange={(e) => setTitle(e.target.value)} /></label><label>Новое начало, по Москве<input type="datetime-local" required value={start} onChange={(e) => setStart(e.target.value)} /></label><label>Новое окончание, по Москве<input type="datetime-local" required min={start} value={end} onChange={(e) => setEnd(e.target.value)} /></label><p>Кого сохранить в предпочтениях — необязательно:</p>{data.participants.length ? data.participants.map((p) => <label className="shortlist-pick" key={p.source_request_id}><input type="checkbox" disabled={!p.can_prefer} checked={selected.includes(p.source_request_id)} onChange={(e) => setSelected(e.target.checked ? [...selected, p.source_request_id] : selected.filter((id) => id !== p.source_request_id))} />{p.name}</label>) : <p>Участников завершённых сделок нет.</p>}</fieldset><p>Предпочтения не резервируют дату. Доступность каждого участника проверяется заново; старые предложения, платежи и подписи остаются в завершённом событии.</p><button className="btn" disabled={busy || loading}>Создать новое событие</button></form>}</>}<button className="secondary" disabled={busy || loading} onClick={() => void load()}>Обновить данные для повтора</button></section>;
}
export function RepeatPreferences({ eventId, onUpdated }: { eventId: string; onUpdated: () => void }) {
  const [data, setData] = useState<Preferences | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async (signal?: AbortSignal) => { setError(""); try { const result = await api<Preferences>(`/events/${eventId}/repeat-preferences`, { signal }); if (!signal?.aborted) setData(result); } catch(e) { if (!signal?.aborted) setError(commerceError(e)); } }, [eventId]);
  useEffect(() => { const c = new AbortController(); void load(c.signal); return () => c.abort(); }, [load]);
  async function add(selection: Selection) { if (!data || busy) return; setBusy(true); setError(""); try { await api(`/events/${eventId}/plan`, { method: "PUT", body: JSON.stringify({ expected_revision: data.revision, expected_context: data.context_token, selections: [...(data.saved_selections || []).filter((s) => s.requirement_id !== selection.requirement_id || s.position !== selection.position), selection] }) }); await load(); setNotice("Участник включён в предварительный состав. Заявка ещё не отправлена."); onUpdated(); } catch(e) { setError(commerceError(e)); } finally { setBusy(false); } }
  if (!error && data?.items.length === 0) return null;
  return <section className="card event-repeat" aria-label="Предпочтения из прошлого события"><h2>Предпочтения из прошлого события</h2>{!data && !error && <p role="status">Проверяем участников для новой даты…</p>}{error && <p role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}<p>Для прошлого состава заново проверяются окно, роли и совместимость. Включение участника не резервирует дату; условия потребуют новых предложений.</p>{data?.items.map((item) => <article key={item.id}><h3>{item.name}</h3>{item.already_selected ? <p>Уже в предварительном составе.</p> : <><ul>{item.problems.map((p) => <li key={p}>{p}</li>)}</ul><button className="secondary" disabled={busy || !item.can_add} onClick={() => void add(item.selection)}>Включить в состав: {item.name}</button></>}</article>)}<button className="secondary" disabled={busy} onClick={() => void load()}>Перепроверить предпочтения</button></section>;
}
