"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { api, getToken } from "@/lib/api";
import { commerceError } from "@/lib/commerce";
const labels: Record<string, string> = { admin: "Администратор", manager: "Менеджер", viewer: "Просмотр" };
export function JoinTeam() {
  const [secret, setSecret] = useState(""); const [authed, setAuthed] = useState(false); const [data, setData] = useState<{ name: string; role: string; can_confirm_offer: boolean } | null>(null); const [error, setError] = useState(""); const [done, setDone] = useState(""); const [busy, setBusy] = useState(false); const [refresh, setRefresh] = useState(0);
  useEffect(() => { const fragment = location.hash.slice(1); if (/^[a-f0-9]{64}$/.test(fragment)) { sessionStorage.setItem("booker.team.pending", fragment); history.replaceState(null, "", location.pathname); } const value = sessionStorage.getItem("booker.team.pending") || ""; setSecret(value); setAuthed(!!getToken()); if (!value) { setError("Откройте ссылку приглашения, которую вам передал организатор"); return; } if (getToken()) api<{ name: string; role: string; can_confirm_offer: boolean; accepted?: boolean }>("/team-invitations/preview", { method: "POST", headers: { "X-Team-Invitation": value } }).then(value => { if (value.accepted) { setDone(value.name); sessionStorage.removeItem("booker.team.pending"); } else setData(value); }).catch(e => setError(commerceError(e))); }, [refresh]);
  async function accept() { setBusy(true); setError(""); try { const result = await api<{ name: string }>("/team-invitations/accept", { method: "POST", headers: { "X-Team-Invitation": secret } }); sessionStorage.removeItem("booker.team.pending"); setDone(result.name); } catch(e) { setError(commerceError(e)); } finally { setBusy(false); } }
  return <main><h1>Приглашение в команду</h1>{error && <p role="alert">{error}</p>}{done ? <p role="status">Вы присоединились: {done}. Пространство доступно в <Link href="/profile">профиле</Link>.</p> : !authed ? <p>Войдите или зарегистрируйтесь с адресом, для которого создано приглашение. <Link href="/login?next=%2Fteam%2Fjoin">Войти</Link></p> : data ? <section className="card"><h2>{data.name}</h2><p>Ваша роль: {labels[data.role] || "Участник"}.{data.can_confirm_offer && " С правом подтверждать предложения."}</p><button className="btn" disabled={busy} onClick={() => void accept()}>Присоединиться к команде</button></section> : !error && <p role="status">Проверяем приглашение…</p>}{!done && authed && <p><button className="btn secondary" disabled={busy} onClick={() => { setError(""); setRefresh(v => v + 1); }}>Проверить ещё раз</button></p>}</main>;
}
