"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { commerceError } from "@/lib/commerce";
import { formatWhen } from "@/lib/format";

const roles: Record<string, string> = { owner: "Владелец", admin: "Администратор", manager: "Менеджер", viewer: "Просмотр" };
type Member = { id: string; name: string; role: string; can_confirm_offer: boolean; is_self: boolean; can_manage: boolean };
type Team = { name: string; seats: number; used: number; reserved: number; can_manage: boolean; can_assign_admin: boolean; members: Member[]; invitations: { id: string; email: string; role: string; expires_at: string }[] };
export function TeamPanel({ orgId }: { orgId: string }) {
  const [data, setData] = useState<Team | null>(null); const [refresh, setRefresh] = useState(0); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [link, setLink] = useState(""); const [email, setEmail] = useState(""); const [role, setRole] = useState("manager"); const [confirm, setConfirm] = useState(false); const [editing, setEditing] = useState<Member | null>(null); const [editedRole, setEditedRole] = useState(""); const [editedConfirm, setEditedConfirm] = useState(false);
  useEffect(() => { const c = new AbortController(); setLoading(true); api<Team>(`/orgs/${orgId}/team`, { signal: c.signal }).then(value => { if (!c.signal.aborted) { setData(value); setError(""); } }).catch(e => { if (!c.signal.aborted) setError(commerceError(e)); }).finally(() => { if (!c.signal.aborted) setLoading(false); }); return () => c.abort(); }, [orgId, refresh]);
  async function mutate(path: string, method: string, body?: unknown) { setBusy(true); setError(""); try { await api(path, { method, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); setEditing(null); setRefresh(v => v + 1); } catch(e) { setError(commerceError(e)); } finally { setBusy(false); } }
  async function invite(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { const payload = { email: email.trim().toLowerCase(), role, can_confirm_offer: confirm && role !== "viewer" }; const key = `team-invite:${orgId}:${JSON.stringify(payload)}`; let secret = sessionStorage.getItem(key); if (!secret) { secret = Array.from(crypto.getRandomValues(new Uint8Array(32)), b => b.toString(16).padStart(2, "0")).join(""); sessionStorage.setItem(key, secret); } await api(`/orgs/${orgId}/team/invitations`, { method: "POST", body: JSON.stringify({ ...payload, secret }) }); setLink(`${location.origin}/team/join#${secret}`); sessionStorage.removeItem(key); setRefresh(v => v + 1); } catch(e) { setError(commerceError(e)); } finally { setBusy(false); } }
  return <section className="card commerce-checkout" aria-label="Команда организации"><h2>Команда{data ? ` · ${data.name}` : ""}</h2>{loading && <p role="status">Загружаем команду…</p>}{error && <p role="alert">{error}</p>}{data && <>
    <p>Участников: {data.used}. Приглашено: {data.reserved}. Мест по тарифу: {data.seats}.</p><p>После окончания тарифа существующая команда сохраняет доступ. Новые участники смогут присоединиться, когда будет свободное место. <Link href="/pricing">Сравнить тарифы</Link>.</p>
    {data.members.map(member => <article key={member.id} style={{ marginTop: "1rem" }}><h3>{member.name}{member.is_self && " · вы"}</h3><p>{roles[member.role] || "Участник"}{member.can_confirm_offer && " · может подтверждать предложения"}</p>
      {editing?.id === member.id ? <form onSubmit={e => { e.preventDefault(); void mutate(`/orgs/${orgId}/team/members/${member.id}`, "PUT", { role: editedRole, can_confirm_offer: editedConfirm, expected_role: editing.role, expected_can_confirm_offer: editing.can_confirm_offer }); }}><label className="commerce-org">Новая роль<select value={editedRole} onChange={e => setEditedRole(e.target.value)}>{Object.entries(roles).filter(([r]) => data.can_assign_admin || ["manager", "viewer"].includes(r)).map(([r, text]) => <option key={r} value={r}>{text}</option>)}</select></label><label><input type="checkbox" checked={editedConfirm} disabled={editedRole === "viewer"} onChange={e => setEditedConfirm(e.target.checked)} /> Право подтверждать предложения</label><div className="commerce-actions"><button className="btn" disabled={busy}>Сохранить права</button><button className="btn secondary" type="button" onClick={() => setEditing(null)}>Отмена</button></div></form> : member.can_manage && <div className="commerce-actions"><button className="btn secondary" type="button" disabled={busy || loading} onClick={() => { setEditing(member); setEditedRole(member.role); setEditedConfirm(member.can_confirm_offer); }}>Изменить права: {member.name}</button><button className="btn secondary" type="button" disabled={busy || loading || (member.role === "owner" && data.members.filter(m => m.role === "owner").length === 1)} onClick={() => void mutate(`/orgs/${orgId}/team/members/${member.id}`, "DELETE")}>Удалить из команды: {member.name}</button></div>}
    </article>)}
    {data.can_manage && <><h3>Пригласить участника</h3><p>Укажите адрес его аккаунта. Скопируйте ссылку и передайте лично. Ссылка действует семь дней; письмо автоматически не отправляется.</p><form onSubmit={e => void invite(e)}><label className="commerce-org">Email участника<input type="email" required maxLength={255} value={email} onChange={e => setEmail(e.target.value)} /></label><label className="commerce-org">Роль приглашённого<select value={role} onChange={e => setRole(e.target.value)}>{Object.entries(roles).filter(([r]) => r !== "owner" && (r !== "admin" || data.can_assign_admin)).map(([r, text]) => <option key={r} value={r}>{text}</option>)}</select></label><label><input type="checkbox" checked={confirm} disabled={role === "viewer"} onChange={e => setConfirm(e.target.checked)} /> Разрешить подтверждать предложения</label><p><button className="btn" disabled={busy || loading || data.used + data.reserved >= data.seats}>Создать приглашение</button></p></form>
      {link && <div><label className="commerce-org">Ссылка приглашения<input readOnly value={link} onFocus={e => e.target.select()} /></label><button className="btn secondary" type="button" onClick={() => void navigator.clipboard.writeText(link).catch(() => setError("Выделите и скопируйте ссылку вручную"))}>Копировать ссылку</button></div>}
      {data.invitations.map(item => <p key={item.id} style={{ overflowWrap: "anywhere" }}>{item.email} · {roles[item.role]} · до {formatWhen(item.expires_at)} <button className="btn secondary" type="button" disabled={busy} onClick={() => void mutate(`/orgs/${orgId}/team/invitations/${item.id}/revoke`, "POST")}>Отозвать: {item.email}</button></p>)}
    </>}
  </>}<p><button className="btn secondary" type="button" disabled={busy || loading} onClick={() => setRefresh(v => v + 1)}>Обновить команду</button></p></section>;
}
